# ==========================================================================
# CRE PROJECT SETTINGS FILE — OmniSentinel
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://virtual.sepolia.eu.rpc.tenderly.co/757f8dff-67a1-4f35-94a4-ab07e1d43670

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://virtual.sepolia.eu.rpc.tenderly.co/757f8dff-67a1-4f35-94a4-ab07e1d43670
